#!/usr/bin/env python3
"""Assemble the standalone PDD node that ships beside the weights on the Hub.

Run it with the ComfyUI venv python (`docs/comfy_notes.md`). Needs no server and
no GPU; copies files.

## Why this exists rather than a hand-copied folder

Bundling the node with the weights means the node's source lives in two places,
and `CLAUDE.md` is blunt about second copies: a copy with no invalidation is a
cache that goes stale silently. So the bundle is GENERATED from the canonical
files and stamped with the commit it came from, and `--check` re-derives it and
reports any difference. A stale bundle is then a red check rather than a
mystery bug report from a stranger running month-old code.

## What it does NOT solve

Regenerating proves the bundle matches the working tree. It does not prove the
working tree matches what is published on the Hub -- that needs a comparison
against the Hub, which `--check` cannot do offline. Push the bundle whenever
this reports drift.

## The dependency surface, which is the reason a bundle is possible at all

`pdd_lora.py` imports a handful of modules from this pack and nothing else of
it; each of those needs only the standard library and `torch`, and one of them
(`vendor_config`) reads the release's config files from the folder beside it.
Every in-pack import is written both relative and absolute, so no file is
modified on the way out. The surface is DERIVED from the files, not typed:
`required_sources` walks the relative imports from `pdd_lora.py`, and the
bundle refuses to build or pass `--check` while `SOURCES` disagrees with it.

Until 2026-09-03 this paragraph said the surface was exactly one module,
`pdd_math`, and `SOURCES` named two files. `pdd_lora.py` had imported
`pdd_observe` and `block_spec` at module level since 2026-08-30 (`e11afd7`),
and `vendor_config` inside `expected_population` since 2026-09-02. Nothing
compared the tuple with the file, so the bundle regenerated at `72b8d42` on
2026-09-03 was uploaded with its README stamp current and three modules
absent, and failed at load on a stranger's machine with
`No module named 'pdd_observe'`. That is the prose-cache failure the docstring
above warns about, in this file's own constant.

    python bench/build_sidecar_node.py --out <the staged Hub repo>/comfyui_minimax_h3_pdd
    python bench/build_sidecar_node.py --out <same> --check

## Where it goes

The bundle is published to the Hub repo `fbjr/MiniMax-H3-Acc-LoRAs-sidecar`,
beside the converted weights it loads, as the folder `comfyui_minimax_h3_pdd/`.
Recorded here because it was not recorded anywhere on 2026-08-29 and had to be
recovered from a link in the staged README -- the `--out` path says where the
bundle is STAGED, which is not the same question as where it is PUBLISHED.

    hf upload fbjr/MiniMax-H3-Acc-LoRAs-sidecar <staged>/comfyui_minimax_h3_pdd comfyui_minimax_h3_pdd

That repo's own `README.md` is hand-written and lives only in the staging
folder -- nothing in this repo generates it, so a notice added to the bundle
README above does NOT reach the page people land on. Both, or neither.
"""

from __future__ import annotations

import argparse
import ast
import filecmp
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent

#: Copied verbatim: the node module and, transitively, every module of this
#: pack it imports. Each in-pack import is written relative-then-absolute, so a
#: flat folder works unchanged. This tuple is what a reader sees; the authority
#: is `required_sources`, which reads the imports off the files, and `build`
#: refuses while the two disagree in either direction.
SOURCES = ("pdd_lora.py", "pdd_math.py", "pdd_observe.py", "block_spec.py",
           "vendor_config.py")

#: Directories copied whole, file by file. `vendor_config.py` reads the
#: release's declared config from `vendor_config/` beside it
#: (`vendor_config.DIR`), and `pdd_lora.expected_population` reads the
#: transformer depth from there when a sidecar is loaded -- so a bundle
#: without the folder imports cleanly and then refuses every file, which is
#: the quiet half of the same defect.
DATA_DIRS = ("vendor_config",)

#: The module the closure is walked from.
ENTRY = "pdd_lora.py"

#: The node code is this repo's, under its own terms -- NOT the MiniMax license
#: that covers the weights it loads. Two licenses in one Hub repo, so they get
#: separate files and the bundle README says which covers what.
LICENSE = "LICENSE"

INIT = '''"""MiniMax H3 Parallel Decoding Distillation LoRA, as a standalone node.

GENERATED by `bench/build_sidecar_node.py` from ComfyUI-h3-explorations at
{commit}. Do not edit here -- edit the source repo and regenerate, or your
change is the one that disappears.

Drop this folder into `custom_nodes/` and restart ComfyUI. It registers one
node, `MiniMaxH3PDDLoRA`, and touches nothing else.
"""

from comfy_api.latest import ComfyExtension, io                    # noqa: F401

from .pdd_lora import MiniMaxH3PDDLoRA


class MiniMaxH3PDDExtension(ComfyExtension):
    async def get_node_list(self):
        return [MiniMaxH3PDDLoRA]


async def comfy_entrypoint() -> MiniMaxH3PDDExtension:
    return MiniMaxH3PDDExtension()
'''

#: A one-line notice pinned to the top of the bundle README, for when a
#: re-upload is not optional -- someone holding the previous copy has to know
#: to replace it. **Delete it once the upload it refers to is no longer the one
#: people are holding**; it is dated news, not documentation, and a stale
#: "update your nodes" line teaches readers to ignore the next real one. Set to
#: "" for no notice.
NOTICE = ("**Updated 2026-09-03.** If your copy fails to load with "
          "`No module named 'pdd_observe'`, replace this folder: the copy "
          "uploaded earlier on 2026-09-03 was missing three of the node's own "
          "modules. The 2026-08-29 copy had a GPU memory leak after a PDD "
          "render; replace that one too.")

README = '''# MiniMaxH3PDDLoRA — standalone node

{notice}The loader for the converted PDD LoRAs in this repo. Drop this folder into
`custom_nodes/` and restart ComfyUI; it registers one node and nothing else.

    custom_nodes/comfyui_minimax_h3_pdd/

Generated from [`ComfyUI-h3-explorations`](https://github.com/fblissjr/ComfyUI-h3-explorations)
at `{commit}`, which is where to file issues or read the rest of the H3 work.
This folder is a copy for convenience — the source repo is authoritative.

**Licensing here is split.** This node's code is MIT, in this folder's
`LICENSE`. The model weights in the parent directory are Model Derivatives of
MiniMax H3 under the MiniMax H3 Community License Agreement, in the repo root's
`LICENSE`. They are different terms covering different files.
'''


def in_pack_imports(name: str) -> set[str]:
    """Modules of this pack that `ROOT/name` imports, read off its AST.

    Counts the RELATIVE spellings only -- `from . import x` and
    `from .x import y` -- at any depth in the file, not just the top:
    `_vendor_config` imports inside a function, and a missing module there is
    a refusal at load time rather than an ImportError at startup, which is the
    quieter of the two. The absolute fallbacks (`import x`) are deliberately
    not read: this pack has a top-level `nodes.py`, so an absolute spelling
    cannot tell ComfyUI's module from ours, while a relative one can only mean
    ours. Every in-pack import in the entry module is written both ways, so
    the relative half is the whole surface.
    """
    tree = ast.parse((ROOT / name).read_text(), filename=name)
    found: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and node.level == 1:
            if node.module:
                found.add(node.module.split(".")[0])
            else:
                found.update(alias.name for alias in node.names)
    return found


def required_sources() -> set[str]:
    """The closure of in-pack imports from `ENTRY`, as file names."""
    todo, seen = [ENTRY], set()
    while todo:
        name = todo.pop()
        if name in seen:
            continue
        seen.add(name)
        todo.extend(f"{mod}.py" for mod in in_pack_imports(name))
    return seen


def surface_drift() -> list[str]:
    """Where `SOURCES` and the files disagree. Empty means they agree."""
    need = required_sources()
    have = set(SOURCES)
    out = [f"{n}: imported by the bundle but not in SOURCES" for n in sorted(need - have)]
    out += [f"{n}: in SOURCES but nothing in the bundle imports it" for n in sorted(have - need)]
    for name in sorted(need):
        if not (ROOT / name).exists():
            out.append(f"{name}: imported by the bundle and absent from {ROOT.name}")
    return out


def data_files() -> list[str]:
    """Relative paths of every file under `DATA_DIRS`, sorted."""
    out = []
    for d in DATA_DIRS:
        for p in sorted((ROOT / d).iterdir()):
            if p.is_file():
                out.append(f"{d}/{p.name}")
    return out


def commit() -> str:
    try:
        out = subprocess.run(["git", "-C", str(ROOT), "rev-parse", "--short", "HEAD"],
                             capture_output=True, text=True, check=True)
        dirty = subprocess.run(["git", "-C", str(ROOT), "status", "--porcelain"] +
                               [str(ROOT / s) for s in SOURCES + DATA_DIRS],
                               capture_output=True, text=True).stdout.strip()
        return out.stdout.strip() + (" (working tree dirty)" if dirty else "")
    except Exception:
        return "unknown"


def build(out: Path, check: bool) -> int:
    drift = surface_drift()
    if drift:
        for d in drift:
            print(f"  SURFACE  {d}")
        print(f"\n{len(drift)} disagreement(s) between SOURCES and the imports in the "
              f"files. Fix SOURCES; a bundle built from it would fail at load.")
        return 1
    rev = commit()
    want = {}
    verbatim = list(SOURCES) + data_files()
    for name in verbatim:
        want[name] = (ROOT / name).read_bytes()
    want["__init__.py"] = INIT.format(commit=rev).encode()
    want["README.md"] = README.format(
        commit=rev, notice=f"{NOTICE}\n\n" if NOTICE else "").encode()

    if check:
        drift = []
        for name, blob in want.items():
            p = out / name
            if not p.exists():
                drift.append(f"{name}: missing from the bundle")
            elif name in verbatim and p.read_bytes() != blob:
                drift.append(f"{name}: differs from {ROOT.name}/{name}")
        if not (out / LICENSE).exists():
            drift.append(f"{LICENSE}: missing from the bundle")
        for d in drift:
            print(f"  DRIFT  {d}")
        if drift:
            print(f"\n{len(drift)} difference(s). Rerun without --check to rebuild, "
                  f"then push the bundle.")
            return 1
        print(f"  ok    bundle matches {ROOT.name} at {rev}")
        return 0

    out.mkdir(parents=True, exist_ok=True)
    for name, blob in want.items():
        (out / name).parent.mkdir(parents=True, exist_ok=True)
        (out / name).write_bytes(blob)
        print(f"  wrote {name}")
    # copied rather than written, so the file stays exactly the one the repo
    # maintains
    shutil.copyfile(ROOT / LICENSE, out / LICENSE)
    print(f"  wrote {LICENSE}  (copied from {ROOT.name}/{LICENSE})")
    print(f"\nbundle at {out}, from {ROOT.name} at {rev}")
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--out", required=True, type=Path)
    ap.add_argument("--check", action="store_true",
                    help="report drift against the source instead of rebuilding")
    args = ap.parse_args(argv)
    return build(args.out, args.check)


if __name__ == "__main__":
    raise SystemExit(main())
