#!/usr/bin/env python3
"""Assemble the standalone PDD node that ships beside the weights on the Hub.

Run it with the ComfyUI venv python (`docs/comfy_notes.md`). Needs no server and
no GPU; copies files.

## Why this exists rather than a hand-copied folder

Bundling the node with the weights means the node's source lives in two places,
and `CLAUDE.md` is blunt about second copies: a copy with no invalidation is a
cache that goes stale silently. So the bundle is GENERATED from the canonical
files and stamped with the commit it came from, and `--check` re-derives it and
reports any difference. A stale bundle is then a red check rather than a
mystery bug report from a stranger running month-old code.

## What it does NOT solve

Regenerating proves the bundle matches the working tree. It does not prove the
working tree matches what is published on the Hub -- that needs a comparison
against the Hub, which `--check` cannot do offline. Push the bundle whenever
this reports drift.

## The dependency surface, which is the reason a bundle is possible at all

`pdd_lora.py` imports exactly one module from this pack, `pdd_math`, and that
one needs only `torch` and `math`. The import is already written to work both
relative and absolute, so neither file is modified on the way out.

    python bench/build_sidecar_node.py --out <the staged Hub repo>/comfyui_minimax_h3_pdd
    python bench/build_sidecar_node.py --out <same> --check
"""

from __future__ import annotations

import argparse
import filecmp
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent

#: Copied verbatim. `pdd_lora` falls back to an absolute `pdd_math` import when
#: it is not inside a package, so a flat folder works unchanged.
SOURCES = ("pdd_lora.py", "pdd_math.py")

#: The node code is this repo's, under its own terms -- NOT the MiniMax license
#: that covers the weights it loads. Two licenses in one Hub repo, so they get
#: separate files and the bundle README says which covers what.
LICENSE = "LICENSE"

INIT = '''"""MiniMax H3 Parallel Decoding Distillation LoRA, as a standalone node.

GENERATED by `bench/build_sidecar_node.py` from ComfyUI-h3-explorations at
{commit}. Do not edit here -- edit the source repo and regenerate, or your
change is the one that disappears.

Drop this folder into `custom_nodes/` and restart ComfyUI. It registers one
node, `MiniMaxH3PDDLoRA`, and touches nothing else.
"""

from comfy_api.latest import ComfyExtension, io                    # noqa: F401

from .pdd_lora import MiniMaxH3PDDLoRA


class MiniMaxH3PDDExtension(ComfyExtension):
    async def get_node_list(self):
        return [MiniMaxH3PDDLoRA]


async def comfy_entrypoint() -> MiniMaxH3PDDExtension:
    return MiniMaxH3PDDExtension()
'''

#: A one-line notice pinned to the top of the bundle README, for when a
#: re-upload is not optional -- someone holding the previous copy has to know
#: to replace it. **Delete it once the upload it refers to is no longer the one
#: people are holding**; it is dated news, not documentation, and a stale
#: "update your nodes" line teaches readers to ignore the next real one. Set to
#: "" for no notice.
NOTICE = ("**Updated 2026-08-29, about three hours after the first upload.** "
          "If you downloaded this folder before then, replace it — the first "
          "copy left the PDD head bank resident on the GPU and made ComfyUI "
          "report a memory leak on every model load after a PDD render.")

README = '''# MiniMaxH3PDDLoRA — standalone node

{notice}The loader for the converted PDD LoRAs in this repo. Drop this folder into
`custom_nodes/` and restart ComfyUI; it registers one node and nothing else.

    custom_nodes/comfyui_minimax_h3_pdd/

Generated from [`ComfyUI-h3-explorations`](https://github.com/fblissjr/ComfyUI-h3-explorations)
at `{commit}`, which is where to file issues or read the rest of the H3 work.
This folder is a copy for convenience — the source repo is authoritative.

**Licensing here is split.** This node's code is MIT, in this folder's
`LICENSE`. The model weights in the parent directory are Model Derivatives of
MiniMax H3 under the MiniMax H3 Community License Agreement, in the repo root's
`LICENSE`. They are different terms covering different files.
'''


def commit() -> str:
    try:
        out = subprocess.run(["git", "-C", str(ROOT), "rev-parse", "--short", "HEAD"],
                             capture_output=True, text=True, check=True)
        dirty = subprocess.run(["git", "-C", str(ROOT), "status", "--porcelain"] +
                               [str(ROOT / s) for s in SOURCES],
                               capture_output=True, text=True).stdout.strip()
        return out.stdout.strip() + (" (working tree dirty)" if dirty else "")
    except Exception:
        return "unknown"


def build(out: Path, check: bool) -> int:
    rev = commit()
    want = {}
    for name in SOURCES:
        want[name] = (ROOT / name).read_bytes()
    want["__init__.py"] = INIT.format(commit=rev).encode()
    want["README.md"] = README.format(
        commit=rev, notice=f"{NOTICE}\n\n" if NOTICE else "").encode()

    if check:
        drift = []
        for name, blob in want.items():
            p = out / name
            if not p.exists():
                drift.append(f"{name}: missing from the bundle")
            elif name in SOURCES and p.read_bytes() != blob:
                drift.append(f"{name}: differs from {ROOT.name}/{name}")
        if not (out / LICENSE).exists():
            drift.append(f"{LICENSE}: missing from the bundle")
        for d in drift:
            print(f"  DRIFT  {d}")
        if drift:
            print(f"\n{len(drift)} difference(s). Rerun without --check to rebuild, "
                  f"then push the bundle.")
            return 1
        print(f"  ok    bundle matches {ROOT.name} at {rev}")
        return 0

    out.mkdir(parents=True, exist_ok=True)
    for name, blob in want.items():
        (out / name).write_bytes(blob)
        print(f"  wrote {name}")
    # copied rather than written, so the file stays exactly the one the repo
    # maintains
    shutil.copyfile(ROOT / LICENSE, out / LICENSE)
    print(f"  wrote {LICENSE}  (copied from {ROOT.name}/{LICENSE})")
    print(f"\nbundle at {out}, from {ROOT.name} at {rev}")
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--out", required=True, type=Path)
    ap.add_argument("--check", action="store_true",
                    help="report drift against the source instead of rebuilding")
    args = ap.parse_args(argv)
    return build(args.out, args.check)


if __name__ == "__main__":
    raise SystemExit(main())
