#!/usr/bin/env python3
"""Which PDD file loads on which checkpoint, read off the files themselves.

Writes `docs/pdd_artifacts.md` from the metadata every converted PDD file
carries (`h3_pdd_loads_on`, `h3_pdd_adaln_form`, `h3_pdd_backbone`,
`h3_pdd_backbone_probe_of`, `h3_pdd_converter_version`), plus the two facts
the files cannot know about themselves: which constant in
`workflows/h3_config.py` names them (so which graphs wire them), and whether
they sit in the archive folder. Nothing here is typed by hand; the one table
`docs/h3_pdd.md` used to carry for this went stale within a day of the files
changing, because sizes and forms are facts the files already know.

Status, derived:

  current    converted by this repo, named by an `h3_config` `*_LORA` constant
  current, unwired
             converted by this repo, in the loras folder, named by no constant
             (the `adaln2688` form: it loads on either base, no shipped graph
             wires it because every shipped graph loads the pruned base)
  archived   under `pdd_archive/`: a superseded conversion kept for the dated
             records and saved graphs that name it; never wire a new graph to it
  reference  not converted by this repo: the alibaba-pai source, or Kijai's
             conversion, read by `bench/compare_pdd_conversions.py` as a control

`--check` regenerates in memory and exits 1 if the committed document differs,
the same shape as `bench/build_prompt_catalogue.py --check`. It needs the
files on disk and says so when they are not; a missing loras folder is exit 2,
not a pass.

    uv run --active --no-sync python bench/pdd_artifact_inventory.py
    uv run --active --no-sync python bench/pdd_artifact_inventory.py --check
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
sys.path.insert(0, str(REPO / "workflows"))
import h3_config  # noqa: E402

LORAS = HERE.parents[2] / "models" / "loras" / "h3"
ARCHIVE = LORAS / "pdd_archive"
OUT = REPO / "docs" / "pdd_artifacts.md"
PATTERN = re.compile(r"pdd|Acc-8Step", re.IGNORECASE)


def _named_in_config() -> dict[str, str]:
    """{basename: constant} for every `*_LORA` constant naming a PDD file."""
    out = {}
    for name in dir(h3_config):
        if name.endswith("_LORA"):
            value = getattr(h3_config, name)
            if isinstance(value, str) and PATTERN.search(value):
                out[Path(value).name] = name
    return out


def inventory() -> list[dict]:
    from safetensors import safe_open
    named = _named_in_config()
    rows = []
    for folder in (LORAS, ARCHIVE):
        if not folder.exists():
            continue
        for path in sorted(folder.glob("*.safetensors")):
            if not PATTERN.search(path.name):
                continue
            with safe_open(path, framework="pt") as f:
                meta = f.metadata() or {}
                keys = list(f.keys())
            ours = "h3_pdd_converter_version" in meta
            if folder == ARCHIVE:
                status = "archived"
            elif not ours:
                status = ("reference (alibaba-pai source)"
                          if any(k.startswith("transformer_blocks.") for k in keys)
                          else "reference (Kijai's conversion)")
            elif path.name in named:
                status = f"current (`h3_config.{named[path.name]}`)"
            else:
                status = "current, unwired"
            rows.append({
                "file": (f"pdd_archive/{path.name}" if folder == ARCHIVE
                         else path.name),
                "status": status,
                "converter": meta.get("h3_pdd_converter_version", "-") if ours else "-",
                "backbone": meta.get("h3_pdd_backbone", "full" if ours else "-"),
                "adaln": (meta.get("h3_pdd_adaln_form")
                          or ("baked" if any(k.startswith("h3_pdd.adaln_baked.") for k in keys)
                              else "2688" if any(k.startswith("h3_pdd.adaln.") for k in keys)
                              else "-")) if ours else "-",
                "probe_of": meta.get("h3_pdd_backbone_probe_of", "none") if ours else "-",
                "loads_on": (meta.get("h3_pdd_loads_on")
                             or (f"the pruned build only ({meta['h3_pdd_pruned_base']})"
                                 if meta.get("h3_pdd_pruned_base") else "either build")) if ours else "-",
                "tensors": len(keys),
            })
    return rows


def render(rows: list[dict]) -> str:
    lines = [
        "# PDD artifacts: which file, on which checkpoint",
        "",
        "GENERATED by `bench/pdd_artifact_inventory.py` from the files' own",
        "metadata and `workflows/h3_config.py`. Do not hand-edit; regenerate, and",
        "run it with `--check` before trusting this page. `docs/h3_pdd.md` explains",
        "the two adaln forms and the bake contract this table only reports.",
        "",
        "## Rule of thumb",
        "",
        "- Every shipped PDD graph loads a **pruned** int8_convrot base and the",
        "  `..._pdd_8step_comfy` file for its partition. That file's adaln update",
        "  is baked into the pruned checkpoint's curve basis and it refuses an",
        "  unpruned base.",
        "- The `..._adaln2688_comfy` file carries the adaln update in the full",
        "  2688-dim time space and loads on **either** base; on a pruned one it",
        "  takes the slower runtime injection. No shipped graph wires it.",
        "- A `stripped` file (none exists yet) is cut against ONE baked checkpoint",
        "  and loads on nothing else; the node checks identity, not the name.",
        "- Files under `pdd_archive/` are superseded conversions kept for the",
        "  dated records and saved graphs that name them. Do not wire new graphs",
        "  to them.",
        "- The node decides by the loaded model's observables and the file's",
        "  probe, never by filename. Loading the wrong pairing is refused with a",
        "  message that names the fix.",
        "",
        "## Inventory",
        "",
        "| file | status | converter | backbone | adaln form | probe cut from | loads on | tensors |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(f"| `{r['file']}` | {r['status']} | {r['converter']} | "
                     f"{r['backbone']} | {r['adaln']} | {r['probe_of']} | "
                     f"{r['loads_on']} | {r['tensors']} |")
    lines += [
        "",
        "Converter versions: 1 carried no backbone probe; 2 probed int8 codes only",
        "and is refused by the node on a stripped file; 3 probes codes and row",
        "scales from the paired checkpoint and asserts the release's population.",
        "",
    ]
    return "\n".join(lines)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the committed document differs from a "
                         "fresh render")
    args = ap.parse_args(argv)
    if not LORAS.exists():
        print(f"DID NOT RUN: {LORAS.relative_to(HERE.parents[2])} is not on "
              f"this box. Nothing was inventoried, which is not a pass.")
        return 2
    rows = inventory()
    if not rows:
        print("DID NOT RUN: no PDD files found; nothing was inventoried.")
        return 2
    text = render(rows)
    if args.check:
        current = OUT.read_text() if OUT.exists() else ""
        if current != text:
            print(f"STALE: {OUT.relative_to(REPO)} differs from the files on "
                  f"disk; regenerate it.")
            return 1
        print(f"  ok    {OUT.relative_to(REPO)} matches {len(rows)} file(s) "
              f"on disk")
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(REPO)} ({len(rows)} file(s))")
    for r in rows:
        print(f"  {r['file']:70s} {r['status']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
